### ISSUE TITLE
Build error in CFAC 1.5.0 - _gsl_sf_legendre_Plm_array

### ISSUE THREAD

**Issue by mauriceleutenegger** [fnevgeny/cfac#1]
I am building CFAC 1.5.0 on OS X 10.10.5. Here are versions for key software:

```
    >gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 7.0.2 (clang-700.1.81)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

    >gfortran-mp-4.9 --version
    GNU Fortran (MacPorts gcc49 4.9.3_0) 4.9.3

    >port list gsl
    gsl                            @2.1            math/gsl
```

Here is the error excerpted from the tail of the build log:

```
    gcc -o sfac sfac.o stoken.o ../faclib/cfac_faclib.a ../coul/cfac_coul.a  -L/opt/local/lib/ -lsqlite3 -lgsl -lgslcblas   -L/opt/local/lib/gcc49/gcc/x86_64-apple-darwin14/4.9.3 -L/opt/local/lib/gcc49/gcc/x86_64-apple-darwin14/4.9.3/../../.. -lgfortran -lquadmath -lm
    Undefined symbols for architecture x86_64:
     "_gsl_sf_legendre_Plm_array", referenced from:
          _SaveAsymmetry in cfac_faclib.a(recombination.o)
    ld: symbol(s) not found for architecture x86_64
```

Here is a search for the symbol in the GSL library:

<pre><code>
>nm /opt/local/lib/libgsl.dylib | grep _gsl_sf_legendre_Plm_array
>nm /opt/local/lib/libgsl.dylib | grep legendre
00000000000fa904 T _gsl_sf_legendre_H3d
00000000000fa87c T _gsl_sf_legendre_H3d_0
00000000000f93fd T _gsl_sf_legendre_H3d_0_e
00000000000fa8c0 T _gsl_sf_legendre_H3d_1
00000000000f95b6 T _gsl_sf_legendre_H3d_1_e
00000000000fa65d T _gsl_sf_legendre_H3d_array
00000000000f9959 T _gsl_sf_legendre_H3d_e
0000000000103e4b T _gsl_sf_legendre_P1
0000000000102fce T _gsl_sf_legendre_P1_e
0000000000103e51 T _gsl_sf_legendre_P2
0000000000102fe2 T _gsl_sf_legendre_P2_e
0000000000103e77 T _gsl_sf_legendre_P3
000000000010301e T _gsl_sf_legendre_P3_e
0000000000103ea8 T _gsl_sf_legendre_Pl
00000000001033f2 T _gsl_sf_legendre_Pl_array
00000000001034ce T _gsl_sf_legendre_Pl_deriv_array
000000000010308f T _gsl_sf_legendre_Pl_e
0000000000103eec T _gsl_sf_legendre_Plm
00000000001036f7 T _gsl_sf_legendre_Plm_e
00000000000fec57 T _gsl_sf_legendre_Q0
00000000000fe045 T _gsl_sf_legendre_Q0_e
00000000000fec9b T _gsl_sf_legendre_Q1
00000000000fe263 T _gsl_sf_legendre_Q1_e
00000000000fecdf T _gsl_sf_legendre_Ql
00000000000fe4b5 T _gsl_sf_legendre_Ql_e
00000000000fa93e T _gsl_sf_legendre_array
00000000000fa950 T _gsl_sf_legendre_array_e
00000000000fb067 T _gsl_sf_legendre_array_index
00000000000fe02b T _gsl_sf_legendre_array_n
00000000000fd2d3 T _gsl_sf_legendre_deriv2_alt_array
00000000000fd2e5 T _gsl_sf_legendre_deriv2_alt_array_e
00000000000fc52a T _gsl_sf_legendre_deriv2_array
00000000000fc53c T _gsl_sf_legendre_deriv2_array_e
00000000000fbae7 T _gsl_sf_legendre_deriv_alt_array
00000000000fbaf9 T _gsl_sf_legendre_deriv_alt_array_e
00000000000fb07b T _gsl_sf_legendre_deriv_array
00000000000fb08d T _gsl_sf_legendre_deriv_array_e
00000000000fb052 T _gsl_sf_legendre_nlm
0000000000103f30 T _gsl_sf_legendre_sphPlm
0000000000103a10 T _gsl_sf_legendre_sphPlm_e
00000000000fa49f t _legendre_H3d_lnnorm
</code></pre>

From the GSL manual:

Function: int gsl_sf_legendre_Plm_array (int lmax, int m, double x, double result_array[])
Function: int gsl_sf_legendre_Plm_deriv_array (int lmax, int m, double x, double result_array[], double result_deriv_array[])

These functions are now deprecated and will be removed in a future release; see gsl_sf_legendre_array and gsl_sf_legendre_deriv_array. 

I would interpret that to mean that gsl_sf_legendre_Plm_array should still be supported in this release, but apparently the documentation doesn't match the reality on the ground.

**Comment by fnevgeny** [comment]
Yes, it's a problem of GSL folks who jumped from warning (2.0, October 2015) to disabling (2.1, November 2015) the old interface in a just few weeks. You can either downgrade GSL to <= 2.0 or recompile 2.1 with the respective flag enabled. Alternatively, you can disable the calls to gsl_sf_legendre_Plm_array() in recombination.c. SaveAsymmetry() is anyway undocumented and will be removed in 1.6.0.
