### ISSUE TITLE
Configure error: could not find required version of GSL

### ISSUE THREAD

**Issue by Plasdom** [fnevgeny/cfac#12]
I am trying to build cFAC and am failing at the configure stage. After running ./configure, the output is:

```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gfortran... gfortran
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether gfortran accepts -g... yes
checking how to get verbose linking output from gfortran... -v
checking for Fortran 77 libraries of gfortran...  -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../.. -lgfortran -lm -lquadmath
checking for a BSD-compatible install... /usr/bin/install -c
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking for ar... ar
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working memcmp... yes
checking for ANSI C header files... (cached) yes
checking whether isfinite is declared... yes
checking for cblas_dgemm in -lgslcblas... no
checking for gsl_odeiv2_driver_apply in -lgsl... no
configure: error: could not find required version of GSL
```

I have encountered the same error with multiple versions of GSL installed (1.16, 1.8, 2.1 and 2.7.1).

I have tried building cFAC on a Red Hat HPC system (Red Hat Enterprise Linux 8.5), as well as on macOS v12.5.1. I've had the same issue on both systems. On the linux system, GSL is pre-built and loaded to my environment

Apologies if this is an obvious fix, but I'm not sure what's missing from my GSL install.

**Comment by fnevgeny** [comment]
Please attach config.log

**Comment by Plasdom** [comment]
[config.log](https://github.com/fnevgeny/cfac/files/9526187/config.log)

This is the config.log for the Red Hat configure attempt.

**Comment by fnevgeny** [comment]
```
configure:5055: gcc -o conftest -O2 -fno-common -Wall -Wextra -pedantic -Wno-sign-compare -Wno-unused-parameter   conftest.c -lgsl   >&5
/usr/bin/ld: cannot find -lgsl
```

Evidently, the linker cannot find the library. Apparently, you didn't install it properly. Did you use yum?

**Comment by Plasdom** [comment]
On the linux system GSL is pre-built by system admins and loaded with 'module load gsl'. 

On my macOS attempt I built GSL from source. Running make check passes all tests. GSL is installed to /usr/local/...

**Comment by fnevgeny** [comment]
> On the linux system GSL is pre-built and loaded with 'module load gsl'.

What "module" does is up to the sysadmin who (mis)configured it. Find any short GSL demo (e.g., from its test suite) and try to compile manually.

> On my macOS attempt I built GSL from source. Running make check passes all tests. GSL is installed to /usr/local/...

Is /usr/local/... in the default linker and compiler paths?

Run `./configure --help` and see which options are available. Likely, you'll want to use `--with-extrainc` and `--with-extralib`.

**Comment by Plasdom** [comment]
Ok, it's likely a GSL issue then and not cFAC. Thanks for your help.
