### ISSUE TITLE
CMULTIP missing?

### ISSUE THREAD

**Issue by NaciCankaya** [fnevgeny/cfac#13]
After building cfac and running make check I encounter an issue:

make[1]: Entering directory '/home/Naci/cfac-1.7.0/coul'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/coul'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/faclib'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/faclib'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/sfac'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/sfac'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/doc'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/demo'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/demo'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/cfacdb'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/cfacdb'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/coul'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/coul'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/faclib'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/faclib'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/sfac'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/sfac'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/doc'
make[1]: Entering directory '/home/Naci/cfac-1.7.0/demo'
make[2]: Entering directory '/home/Naci/cfac-1.7.0/demo/structure'
../../sfac/sfac.exe test.sf
 Tests passed!
make[2]: Leaving directory '/home/Naci/cfac-1.7.0/demo/structure'
make[2]: Entering directory '/home/Naci/cfac-1.7.0/demo/pirr'
../../sfac/sfac.exe test.sf
 Tests passed!
make[2]: Leaving directory '/home/Naci/cfac-1.7.0/demo/pirr'
make[2]: Entering directory '/home/Naci/cfac-1.7.0/demo/aidr'
../../sfac/sfac.exe test.sf
 Tests passed!
make[2]: Leaving directory '/home/Naci/cfac-1.7.0/demo/aidr'
make[2]: Entering directory '/home/Naci/cfac-1.7.0/demo/ionization'
../../sfac/sfac.exe test.sf
 Tests passed!
make[2]: Leaving directory '/home/Naci/cfac-1.7.0/demo/ionization'
make[2]: Entering directory '/home/Naci/cfac-1.7.0/demo/excitation'
../../sfac/sfac.exe test.sf
 * This version of cFAC was compiled without the CMULTIP module.
 * Please see the README file for instructions.
make[2]: *** [../Make.common:21: lev.asc] Aborted
make[2]: *** Deleting file 'lev.asc'
make[2]: Leaving directory '/home/Naci/cfac-1.7.0/demo/excitation'
make[1]: *** [Makefile:8: check] Error 1
make[1]: Leaving directory '/home/Naci/cfac-1.7.0/demo'
make: *** [Makefile:21: check] Error 1

Why is CMULTIP deactivated by default? How do I activate it? I need to run CETable, which seems to need CMULTIP. 
I do not find the module mentioned in any Makefile or Make.conf etc.

Thanks,
Naci

**Comment by fnevgeny** [comment]
It's a licensing issue. Please read the README file. It explains both why and how.

**Comment by NaciCankaya** [comment]
Thank you for the quick response. Even with the README file in front of me, I did not see the connection to any licensing issues, now I finally know what was the problem!
