### ISSUE TITLE
cFAC inexplicably excluding higher level indices from tr files

### ISSUE THREAD

**Issue by NaciCankaya** [fnevgeny/cfac#14]
For some reason, at some point the energy levels are excluded from transition calculations. This is a pattern I observed across multiple example input/output examples. In the examples I attached here, one can see how -for some reason- levels with indices exceeding 150 do not appear in the tr table.

This does not seem to originate from physics or from settings of my own choosing.

[Xe8+.txt](https://github.com/user-attachments/files/18009574/Xe8%2B.txt)
[8lev.txt](https://github.com/user-attachments/files/18009577/8lev.txt)
[8tr.txt](https://github.com/user-attachments/files/18009579/8tr.txt)

Also, this seems to be an issue with the cFAC only, not with the FAC.

**Comment by fnevgeny** [comment]
Levels with ID > 150 are from the next charge state (45 electrons). In `TransitionTable()`, you only list groups belonging to nele=46.

**Comment by NaciCankaya** [comment]
This is not the case. The lev file demonstrates how the Xe8+ levels include indices up to 49219, only after then the Xe9+ levels start.

**Comment by fnevgeny** [comment]
I cannot reproduce it.

**Comment by fnevgeny** [comment]
Your [8lev.txt](https://github.com/user-attachments/files/18009577/8lev.txt) file contains, e.g., "4d8 4f2" configurations which are absent in [Xe8+.txt](https://github.com/user-attachments/files/18009574/Xe8%2B.txt).

**Comment by NaciCankaya** [comment]
My apologies. Trying to reproduce it myself, I found out that there was a confusion on my side. You can feel free to delete this thread.

**Comment by NaciCankaya** [comment]
I think I have encountered the same issue again and it should be reproducible now. It seems to only appear when generating large datasets. Example input and output files are attached.

[Xe6+.txt](https://github.com/user-attachments/files/18061878/Xe6%2B.txt)
[Xe7+.txt](https://github.com/user-attachments/files/18061879/Xe7%2B.txt)
[6lev.txt](https://github.com/user-attachments/files/18061890/6lev.txt)
[6tr.txt](https://github.com/user-attachments/files/18061891/6tr.txt)

We can see how in the tr file, levels above an index of 803 are not included. This behavior repeats for other ions and can be observed when running the Xe7+.txt input file as well.

**Comment by fnevgeny** [comment]
Levels above 803 belong to the next charge state.
