### ISSUE TITLE
makefile in cfacdb

### ISSUE THREAD

**Issue by fujiisoup** [fnevgeny/cfac#2]
Hi.

I had a trouble in installing cfac to ubuntu 16.04.
The problem was in [cfacdb/Makefile](https://github.com/fnevgeny/cfac/blob/master/cfacdb/Makefile#L47)

```
cfacdbu.1: cfacdbu$(EXE)
	help2man -s 1 -N cfacdbu$(EXE) -n "CFACDB utility" -S "cFAC" -o $@
```

In my environment, it should be 
```
cfacdbu.1: cfacdbu$(EXE)
	help2man -s 1 -N ./cfacdbu$(EXE) -n "CFACDB utility" -S "cFAC" -o $@
```

I can send a PR if necessary (and if it works in other envirionment).

**Comment by fnevgeny** [comment]
Thanks! Fixed.

**Comment by fujiisoup** [comment]
Thanks!
