### ISSUE TITLE
Improvement in README

### ISSUE THREAD

**Issue by fujiisoup** [fnevgeny/cfac#3]
I found there are some missing steps in `installation` section in README.
I will send a PR.

**Comment by fnevgeny** [comment]
Thanks,

As a general comment, there should be a separation of the compilation/installation instructions for usual users and developers. By the latter I mean those working with git checkouts. Usual users are supposed to download release tarballs which already have configure script, manual.pdf etc generated, so they do not need the respective tools.

It should be clearly stated that non-release snapshots may contain bugs, so an average physicist should be **really** discouraged of using them. A bug in a sci software is much worse than a bug in an editor or like... A published paper with wrong results is not so easy to "fix". Of course, you understand it.

**Comment by fujiisoup** [comment]
@fnevgeny 
Thanks for the reply.

> Usual users are supposed to download release tarballs which already have configure script, manual.pdf etc generated, so they do not need the respective tools.

I see. Thank you for the information.
I don't see the location of the release tarballs. 
As more users (including me) download software from github recently,
is it possible to write its link on the README?

> It should be clearly stated that non-release snapshots may contain bugs, so an average physicist should be really discouraged of using them. 

Do you mean the master-branch on github is worse than the released snapshot?
I personally think that the master-branch (or stable or release branch) should be the best codes as far as the developers believe (better than the previous release).
Some experimental implementation can be kept in another branch such as dev-branch.

I agree that it is difficult to fix the published paper, but I also think it is more difficult to finish up a *bug-less* software.
All we can do might be to fix bugs incremental manner and to write down the software version used in our work (or even the github commit id) on scientific papers.

**Comment by fnevgeny** [comment]
@fujiisoup
> I don't see the location of the release tarballs.

https://github.com/fnevgeny/cfac/releases, e.g., https://github.com/fnevgeny/cfac/releases/download/v1.6.1/cfac-1.6.1.tar.gz

It should certainly be described in README.

> Do you mean the master-branch on github is worse than the released snapshot?

Yes. Less tested.

> I personally think that the master-branch (or stable or release branch) should be the best codes as far as the developers believe (better than the previous release).

Then everybody should have preferred Debian-testing vs. -stable :).

> All we can do might be to fix bugs incremental manner and to write down the software version used in our work (or even the github commit id) on scientific papers.

Right, there is such a thing as reproducibility. When I say "this was calculated using cfac-1.6.1", I know everybody can download that specific version and get the same results. With a snapshot, it becomes impossible, at least for anybody not versed in git. And most physicists are not...

**Comment by fujiisoup** [comment]
> https://github.com/fnevgeny/cfac/releases, e.g., 

I did not notice it. Thanks.

> Then everybody should have preferred Debian-testing vs. -stable :).

Then, I understand that you keep release versions by tag rather than branch.
I personally like to have `stable` branch that tracks the latest release, 
but it might depend on developers' preference.
[numpy](https://github.com/numpy/numpy) does not have `stable` but [xarray](https://github.com/pydata/xarray) has.

**Comment by fnevgeny** [comment]
> Then, I understand that you keep release versions by tag rather than branch.

Right. Old habits from CVS :).
