### ISSUE TITLE
basic cr-model

### ISSUE THREAD

**Issue by fujiisoup** [fnevgeny/cfac#5]
Hi @fnevgeny 

[faq](https://github.com/fnevgeny/cfac/blob/master/doc/faq.tex) says that `cfac` does not support a simple cr-model which was bundled in the original `fac`.

What is the reason for this omission?
Is there any possibility to include a basic cr-model to `cfac`?

**Comment by fnevgeny** [comment]
Hi,
The simple model is too simple for my own needs (I wrote a CR code quite some time ago). So to cut on maintenance time I just dropped it from cfac...

**Comment by fujiisoup** [comment]
> The simple model is too simple for my own needs (I wrote a CR code quite some time ago).

Thanks for the information.
Do you mind if anyone contributes a simple cr-model to this repository?

I understand it may increase the maintenance burden, but an appropriate design of test codes and a continuous integration system may save most part of it.

As most of the atomic codes are *closed* except for `fac`,
I am really excited to have it on github and if possible I want to contribute to this open atomic-molecular study.

**Comment by fnevgeny** [comment]
Well, I don't know. Maybe try to see what it would be like to introduce it back in the current cfac tree... It will have to use the cfacdb library to access the atomic data.

**Comment by fujiisoup** [comment]
Thanks for the information.

Please let me clarify, what I might misunderstand;
Is `fac` still being maintained?

I thought `cfac` is replacing `fac` and `fac` is no longer maintained, but I just noticed several versions of `fac` has been released recently.

**Comment by fnevgeny** [comment]
Yes, the original FAC is still being maintained. As far as I am concerned, only bug fixes go there.

**Comment by fujiisoup** [comment]
I see. Then, I should use `fac` instead.
Thank you for the information.
Closing this issue.
