### ISSUE TITLE
git repo lacks configure

### ISSUE THREAD

**Issue by kdere** [fnevgeny/cfac#6]
it is in the v1.6.1 release

**Comment by fnevgeny** [comment]
`configure` is autogenerated, so not kept under VC. The _release_ [tarball](https://github.com/fnevgeny/cfac/releases/download/v1.6.1/cfac-1.6.1.tar.gz) does include it.

**Comment by kdere** [comment]
thanks for the reply.  However, I did find it confusing.

**Comment by fnevgeny** [comment]
It's a standard practice in many projects.
