### ISSUE TITLE
problem with CIRadialQkBED / isfinite ?

### ISSUE THREAD

**Issue by vlad365** [fnevgeny/cfac#7]
When I run "make", it complains about CIRadialQkBED/isfinite and exits with error.
Is this my oversight with configure or a code problem? 
I appreciate your help. 
Thank you for your time.

compare -Wno-unused-parameter ionization.c
ionization.c: In function 'CIRadialQkBED':
ionization.c:558:3: warning: implicit declaration of function 'isfinite' [-Wimplicit-function-declaration]
   if (!isfinite(*bethe)) {
   ^
<...>
../faclib/cfac_faclib.a(ionization.o): In function `CIRadialQkBED':
ionization.c:(.text+0x120a): undefined reference to `isfinite'
collect2: error: ld returned 1 exit status
make[1]: *** [sfac] Error 1

**Comment by fnevgeny** [comment]
Hi,
Which OS/version do you use?

**Comment by fnevgeny** [comment]
And what is this `compare` in `compare -Wno-unused-parameter ionization.c`?

**Comment by vlad365** [comment]
Hi --
1) Linux  2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
2) Sorry -- the line with "compare" got cut off, the full make message line read as follows:
gcc -c -I.. -I../include -I.  -O2 -fno-common -Wall -Wextra -pedantic -Wno-sign-compare -Wno-unused-parameter ionization.c

**Comment by fnevgeny** [comment]
Is this a RH or Centos (which version)?

**Comment by vlad365** [comment]
This is CentOS 6.8

**Comment by vlad365** [comment]
It is actually CentOS 6.9 if it matters.

**Comment by fnevgeny** [comment]
Try replacing isfinite() with finite() in the affected file.

**Comment by vlad365** [comment]
Thank you again -- I replaced isfinite() with finite() in one instance in the ionization.c file and it solved the make problem.
