### ISSUE TITLE
Python interface to cfacdb

### ISSUE THREAD

**Issue by mfkasim1** [fnevgeny/cfac#9]
Hi Evgeny,

I am working on a Python script that somehow needs an interface to cfacdb, and I think it might be useful if there's a Python interface built in cfac.
Do you agree if I work on the Python interface of cfacdb and integrate it here if you're willing?
If so, do you have any preference on the directory structure (e.g. should I make a "python" directory on root or somewhere you think might fit) and what should be included in the directory (e.g. tests, module installer using pip, etc)?

Thanks,
Muhammad

**Comment by fnevgeny** [comment]
Hi, sorry, I was abroad. I am not big fan of Python, but why not, please go ahead. I do not think exact details of directory structure are really important at this point. Are you going to use SWIG?
